import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar/Navbar'
import './globals.css'
import Footer from '../components/Footer/Footer';
import { auth } from "@/lib/firebase";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const unsubscribe = auth.onAuthStateChanged(() => {})
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar count={2} ></Navbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  ) 
}
